### ISSUE TITLE
support for extended id3/ogg fields

### ISSUE THREAD

**Issue by nikmartin** [voltraco/node-taglib2#9]
Hey there, I'm trying to use taglib2 to write ID3 and ogg xiphComments, specifically the field 'grouping' which is ID3 frame 'TIT1'. All I seem to be able to write and read are the common fields like:
  ```
title:
  artist:
  albumartist:
  discnumber:
  tracknumber:
  album: 
  track:
  year: 
  pictures: []

```
Is it possible to read and write other fields besides these? I'm a DJ and need to overload the grouping field with song edit information (radio edit, short edit, extended edit, intro edit, etc), keeping the title of the song intact in the title field.
